version: '3'
services:
    usersDB:
        image: redis
        container_name: users
        expose:
            - 6379

    gameDB:
        image: redis
        container_name: game
        ports:
            - 9000:6379
        expose:
            - 9000

    api:
        image: grapple_api
        links:
            - usersDB
        environment:
            - REDIS_URL=redis://users
        ports:
            - 8080:8080

    socket:
        image: socket
        ports:
            - 7070:7070
        environment:
            - REDIS_URL=redis://game
